/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import DAO.DepenseDAO;
import DAO.NoteFraisDAO;
import DAO.UtilisateurDAO;
import DAO.ValidationDAO;
import Metier.NoteFrais;
import Metier.Utilisateur;
import Metier.Validation;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author coolye
 */
public class ListeSalarieAtt extends javax.swing.JFrame {

    /**
     * Creates new form ListeSalarieAtt
     */
    public ListeSalarieAtt() throws SQLException {
        initComponents();
        this.setTitle("Liste des salariés en attente de validation");
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("images/icone.png"));
       getContentPane().setBackground(new Color(13, 110, 189));
        UtilisateurDAO utilisateurDAO = new UtilisateurDAO();
        ValidationDAO validationDAO = new ValidationDAO();
        ArrayList<Utilisateur> listUtilisateur = utilisateurDAO.listUtilisateur();
        
        JTable jTable_Utilisateur = tabSalarieAttente;
        DefaultTableModel dm = (DefaultTableModel) jTable_Utilisateur.getModel();
        for(Utilisateur oneUtilisateur : listUtilisateur){
            
            NoteFraisDAO notefraisDAO = new NoteFraisDAO();
            DepenseDAO depenseDAO = new DepenseDAO();
            ArrayList<NoteFrais> listNotefrais = notefraisDAO.listNoteFraisById(oneUtilisateur.getId_Utilisateur());
            int nbreDepense = 0;
            int nbreDepenseValider = 0;
            
            for(NoteFrais theNotefrais : listNotefrais){
                nbreDepense += depenseDAO.nbreDepenseByIdNotefrais(theNotefrais.getId_Notefrais());
                nbreDepenseValider += validationDAO.nbreDepenseValiderByIdNotefrais(theNotefrais.getId_Notefrais());
            }
            String statut;
            if (nbreDepense == nbreDepenseValider){
                statut = "Pas de note a valider";
            } else {
                int reste= nbreDepense-nbreDepenseValider;
                statut = "Reste "+reste+" dépense(s) à valider";
                String a[] = {Integer.toString(oneUtilisateur.getId_Utilisateur()), oneUtilisateur.getNom_Utilisateur(), oneUtilisateur.getPrenom_Utilisateur(), oneUtilisateur.getMail_Utilisateur(), statut};
                dm.addRow(a);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabSalarieAttente = new javax.swing.JTable();
        butRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitre.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTitre.setForeground(java.awt.Color.white);
        labelTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitre.setText("Liste des salariés en attente");

        tabSalarieAttente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabSalarieAttente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "email", "nbr note "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabSalarieAttente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSalarieAttenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabSalarieAttente);
        if (tabSalarieAttente.getColumnModel().getColumnCount() > 0) {
            tabSalarieAttente.getColumnModel().getColumn(0).setMinWidth(0);
            tabSalarieAttente.getColumnModel().getColumn(0).setPreferredWidth(0);
            tabSalarieAttente.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        butRetour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        butRetour.setText("Retour");
        butRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butRetour, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addComponent(labelTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitre)
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(butRetour)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRetourActionPerformed
        MenuSalarie uneFenetre = new MenuSalarie();
        uneFenetre.setVisible(true);
        ListeSalarieAtt.this.setVisible(false);
        uneFenetre.setLocationRelativeTo(null);
    }//GEN-LAST:event_butRetourActionPerformed

    private void tabSalarieAttenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSalarieAttenteMouseClicked

    //on récupérele numero de la ligne cliqué
        int ligneSelectionne = tabSalarieAttente.getSelectedRow();
    //on récupère la valeur de la  colonne souhaité de la ligne sélectionné (mettre id dans la dernière colonne chez moi 5 et lui mettre 0 en largeur min et max pour la rendre invisible)
        String Id_Jtable1=(String) tabSalarieAttente.getValueAt(ligneSelectionne,0);
    //convertir en string en int
        int id_Jtable= Integer.parseInt(Id_Jtable1);
    //vérifier si réception dans le log
        System.out.println(id_Jtable);
    //ouvrir la fenêtre visé avec l'id en ref
        DetailSalarie uneFenetre = null;
        try {
            uneFenetre = new DetailSalarie(id_Jtable);
        } catch (SQLException ex) {
            Logger.getLogger(ListeSalarieAtt.class.getName()).log(Level.SEVERE, null, ex);
        }
        uneFenetre.setVisible(true);
        ListeSalarieAtt.this.setVisible(false);

    }//GEN-LAST:event_tabSalarieAttenteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeSalarieAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeSalarieAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeSalarieAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeSalarieAtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListeSalarieAtt().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ListeSalarieAtt.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butRetour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JTable tabSalarieAttente;
    // End of variables declaration//GEN-END:variables
}
