/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author coolye
 */
public class MenuSalarie extends javax.swing.JFrame {

    /**
     * Creates new form MenuSalarie
     */
    public MenuSalarie() {
        initComponents();
        
        this.setTitle("Menu Salarié");
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("images/icone.png"));
       getContentPane().setBackground(new Color(13, 110, 189));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButRetour = new javax.swing.JButton();
        LabTitre = new javax.swing.JLabel();
        ButSalNoteAtt = new javax.swing.JButton();
        butListedessalarie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButRetour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ButRetour.setText("Retour");
        ButRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButRetourActionPerformed(evt);
            }
        });

        LabTitre.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LabTitre.setForeground(java.awt.Color.white);
        LabTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabTitre.setText("Gestion des Salariés");

        ButSalNoteAtt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ButSalNoteAtt.setText("Salariés - Note en attente de validation");
        ButSalNoteAtt.setMaximumSize(new java.awt.Dimension(115, 25));
        ButSalNoteAtt.setMinimumSize(new java.awt.Dimension(115, 25));
        ButSalNoteAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalNoteAttActionPerformed(evt);
            }
        });

        butListedessalarie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        butListedessalarie.setText("Salariés - tous les salariés");
        butListedessalarie.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        butListedessalarie.setMaximumSize(new java.awt.Dimension(115, 25));
        butListedessalarie.setMinimumSize(new java.awt.Dimension(115, 25));
        butListedessalarie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butListedessalarieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButRetour)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(ButSalNoteAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(butListedessalarie, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(LabTitre)
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButSalNoteAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butListedessalarie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(ButRetour)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButRetourActionPerformed
        Accueil uneFenetre = new Accueil();
        uneFenetre.setVisible(true);
        MenuSalarie.this.setVisible(false);
        uneFenetre.setLocationRelativeTo(null);
    }//GEN-LAST:event_ButRetourActionPerformed

    private void butListedessalarieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butListedessalarieActionPerformed
        ListeSalarieVal uneFenetre = null;
        try {
            uneFenetre = new ListeSalarieVal();
        } catch (SQLException ex) {
            Logger.getLogger(MenuSalarie.class.getName()).log(Level.SEVERE, null, ex);
        }
        uneFenetre.setVisible(true);
        MenuSalarie.this.setVisible(false);
        uneFenetre.setLocationRelativeTo(null);
    }//GEN-LAST:event_butListedessalarieActionPerformed

    private void ButSalNoteAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalNoteAttActionPerformed
        ListeSalarieAtt uneFenetre = null;
        try {
            uneFenetre = new ListeSalarieAtt();
        } catch (SQLException ex) {
            Logger.getLogger(MenuSalarie.class.getName()).log(Level.SEVERE, null, ex);
        }
        uneFenetre.setVisible(true);
        MenuSalarie.this.setVisible(false);
        uneFenetre.setLocationRelativeTo(null);
    }//GEN-LAST:event_ButSalNoteAttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSalarie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButRetour;
    private javax.swing.JButton ButSalNoteAtt;
    private javax.swing.JLabel LabTitre;
    private javax.swing.JButton butListedessalarie;
    // End of variables declaration//GEN-END:variables
}
